const crushLines = [
  "Your crush secretly stalks your status updates but pretends not to care.",
  "Your crush once typed a long message to you but deleted it before sending.",
  "If your crush smiles at you twice in one day, it means they thought about you the night before.",
  "Someone very close to you knows your crush likes you but isn’t telling.",
  "Your crush has imagined what it would be like to hold your hand already.",
  "Sometimes your crush saves your name in their phone with a heart emoji, then changes it back before anyone sees.",
  "Your crush has scrolled through your old pictures late at night.",
  "Even when your crush ignores you, they still secretly care a lot.",
  "Your crush replays your voice notes more times than you think.",
  "When your crush laughs at your jokes, sometimes it’s because they actually find you funny, not just polite.",
  "Your crush avoids eye contact not because they don’t like you, but because they like you too much.",
  "Sometimes your crush tells their friends little things you said.",
  "If your crush calls you by a nickname, it’s because they’ve already made space for you in their heart.",
  "Your crush has dreamt about you at least once this month.",
  "Your crush notices your WhatsApp DP changes even before you expect it.",
  "Sometimes your crush checks if you’re online and waits to see if you’ll text first.",
  "Your crush knows your favorite emoji even if you’ve never told them.",
  "Your crush has imagined introducing you to someone important in their life.",
  "Your crush sometimes smiles alone when they think about a memory with you.",
  "Even if your crush says ‘we’re just friends,’ deep down there’s a part of them that wonders what if…",
  "Your crush has written your name in their notes app just to see how it looks.",
  "Sometimes your crush types your name into search just to find old chats.",
  "Your crush has compared others to you and found they don’t match up.",
  "Your crush has imagined what your voice sounds like when you say their name softly.",
  "Your crush once changed their profile picture hoping you’d notice.",
  "Your crush sometimes waits for you to post before they post.",
  "Your crush has told their closest friend about you at least once.",
  "If your crush jokes with you a lot, it’s because they want to hide deeper feelings.",
  "Your crush has liked something you posted, deleted it, then liked again.",
  "Sometimes your crush opens your chat just to smile at your last message.",
  "Your crush secretly knows your birthday even if you never said it.",
  "Your crush once considered texting you good morning but held back.",
  "Your crush gets a little jealous when they see you talk to someone else.",
  "Sometimes your crush watches your story all the way through, hoping you’ll notice.",
  "Your crush has imagined dancing with you even without music playing.",
  "Your crush sometimes rehearses what to say before messaging you.",
  "Your crush smiles when they hear a song that reminds them of you.",
  "Your crush has screenshot something you posted, even if you’ll never know.",
  "Your crush sometimes lingers longer in places where you might appear.",
  "Your crush once pretended not to care but deep down felt the opposite.",
  "Sometimes your crush tries to act busy so you’ll chase them.",
  "Your crush has whispered your name to themselves before.",
  "Your crush secretly hopes you’ll send a random text first.",
  "Your crush sometimes stares at your chat waiting for you to type.",
  "Your crush once drafted a confession but deleted it at the last second.",
  "Your crush sometimes copies your texting style without realizing it.",
  "Your crush laughs harder at your jokes than anyone else’s.",
  "Your crush sometimes scrolls to the top of your chat just to see how it started.",
  "Your crush once replayed your voice note three times because of your laugh.",
  "Your crush sometimes plans excuses just to text you.",
  "Your crush knows your favorite color even if you’ve never said it.",
  "Your crush sometimes puts extra effort in their DP because of you.",
  "Your crush once sent you a message, deleted it, and regretted it.",
  "Your crush has imagined walking with you late at night.",
  "Your crush sometimes avoids messaging just to see if you’ll miss them.",
  "Your crush secretly loves your typing bubbles more than replies.",
  "Your crush sometimes stays up late hoping you’ll text them first.",
  "Your crush has told someone you make them happy.",
  "Your crush once saved a meme because it reminded them of you.",
  "Your crush sometimes retypes their message five times before sending.",
  "Your crush has thought about your smile more times than you think.",
  "Your crush sometimes gets shy when you compliment them.",
  "Your crush secretly checks your online status at midnight.",
  "Your crush once pretended to be mad just to see if you’d care.",
  "Your crush sometimes wishes you’d call them by a cute nickname.",
  "Your crush has replayed a song because it reminded them of you.",
  "Your crush sometimes acts cold because they’re scared of liking you too much.",
  "Your crush once dreamt about holding your hand.",
  "Your crush sometimes likes your post but hides it from others.",
  "Your crush has imagined sitting next to you in class or work.",
  "Your crush sometimes keeps typing then deleting just to get your attention.",
  "Your crush once smiled at their phone because of your text.",
  "Your crush sometimes looks at your old messages when they miss you.",
  "Your crush once thought of confessing but chickened out.",
  "Your crush sometimes laughs alone when they remember your joke.",
  "Your crush once practiced your name with a heart emoji.",
  "Your crush sometimes stares at your profile longer than they should.",
  "Your crush once wanted to text you ‘I miss you’ but didn’t.",
  "Your crush sometimes reopens your chat even when there’s nothing new.",
  "Your crush has told someone they admire how unique you are.",
  "Your crush once listened to a song on repeat because of you.",
  "Your crush sometimes changes their status hoping you’ll react.",
  "Your crush once smiled randomly thinking of you.",
  "Your crush sometimes wishes you’d notice the small things they do.",
  "Your crush once typed your name in notes with hearts around it.",
  "Your crush sometimes watches your status but hides theirs from you.",
  "Your crush once thought about how your hug would feel.",
  "Your crush sometimes avoids looking at you so you won’t notice their feelings.",
  "Your crush once told someone they find you inspiring.",
  "Your crush sometimes checks your bio to see if it changes.",
  "Your crush once considered asking you out but lost the courage.",
  "Your crush sometimes stares at their phone hoping your name pops up.",
  "Your crush once rehearsed what to say if you asked them about feelings.",
  "Your crush sometimes wishes you’d send a random compliment.",
  "Your crush once imagined celebrating something special with you.",
  "Your crush sometimes tries to hide their smile when you message.",
  "Your crush once replayed a call just to hear your voice again."
];

module.exports = {
  name: "crush",
  description: "Reveal fun and playful crush secrets.",
  execute(sock, m) {
    const line = crushLines[Math.floor(Math.random() * crushLines.length)];
    sock.sendMessage(m.chat, { text: line }, { quoted: m });
  }
};
