module.exports = {
    name: "dare",
    description: "Get a random dare challenge, fun for games.",
    execute(sock, msg, args) {
        const dares = [
            "Send a voice note singing your favorite song.",
            "Type a message using only emojis.",
            "Change your WhatsApp name to something funny for 1 day.",
            "Send a meme from your gallery.",
            "Talk in baby voice for the next 5 minutes.",
            "Confess something silly in the group.",
            "Pretend to be a robot until your next turn.",
            "Say the alphabet backward as fast as you can.",
            "Post a random selfie right now.",
            "Send a sticker that matches your mood.",
            "Do 10 push-ups and say 'done' in chat.",
            "Text the last person you called and say 'I like pizza more than you'.",
            "Send a gif that describes your current life.",
            "Use only one word replies for 10 minutes.",
            "Speak in rhymes until your next turn.",
            "Send a random embarrassing story.",
            "Pretend to be another player until the round ends.",
            "Make a joke and send it in the chat.",
            "Send your most recent screenshot.",
            "Let someone else in the group choose your status.",
            "Send a voice note imitating your favorite celebrity.",
            "Change your profile picture to something silly.",
            "Write your name backward in the chat.",
            "Send the last picture you took.",
            "Send a message using your non-dominant hand.",
            "Send a random fact you know.",
            "Send a flirty line to someone random in the group.",
            "Reply 'ok' to every message for 10 minutes.",
            "Sing a nursery rhyme in the chat.",
            "Send a dare to yourself and do it.",
            "Send a random tongue twister and say it 3 times.",
            "Write a poem in the group right now.",
            "Act like a monkey for the next 5 minutes.",
            "Change your group nickname to 'Clown'.",
            "Speak only in questions for 5 minutes.",
            "Send a funny face picture.",
            "Call someone in the group 'boss' for 1 day.",
            "Pretend to be a teacher and scold the group.",
            "Send your phone’s battery percentage.",
            "Post a random food pic from your gallery.",
            "Make your next 3 messages all caps.",
            "Tell the group your most useless skill.",
            "Act like a baby for 2 minutes.",
            "Type a message blindfolded and send it.",
            "Send a silly audio message.",
            "Do 20 jumping jacks and say 'done'.",
            "Let the group pick your next profile picture.",
            "Make your status 'I love pineapples' for 24h.",
            "Text someone random 'I have a secret'.",
            "Dance to a song and send proof.",
            "Act like a cat in the group chat.",
            "Say 'I’m awesome' after every sentence for 5 min.",
            "Send a video of yourself clapping for 20s.",
            "Send your most recent emoji combo.",
            "Roast yourself in the chat.",
            "Pretend to be the bot for 5 minutes.",
            "Send a random contact name from your phone.",
            "Make a fake confession to the group.",
            "Send a sticker pack you use the most.",
            "Tell the group your most awkward text ever.",
            "Send your most used GIF.",
            "Change your status to 'Married to the bot'.",
            "Talk like a pirate for the next 5 messages.",
            "Send a food recipe (real or fake).",
            "Post the oldest photo in your gallery.",
            "Let someone else pick an emoji for your bio.",
            "Make your DP a cartoon character for a day.",
            "Shout out the group name in a voice note.",
            "Send your browser history (or fake one).",
            "Say 'yes boss' to every message for 5 min.",
            "Send a random YouTube link.",
            "Draw something and send it.",
            "Text 'I’m Batman' to someone random.",
            "Send the weirdest pic you have saved.",
            "Pretend to be a famous person for 5 min.",
            "Make a rap about pineapples and send it.",
            "Pretend you are in love with the bot.",
            "Let someone rename you in the group.",
            "Reply only with stickers for 10 min.",
            "Say a random pickup line.",
            "Pretend to cry in a voice note.",
            "Tell everyone your last dream.",
            "Send a tongue emoji 10 times.",
            "Roast your crush in one sentence.",
            "Send a random number from your contacts.",
            "Act like a news reporter for 2 min.",
            "Do 5 squats and say 'champion'.",
            "Pretend you’re an animal of choice for 3 min.",
            "Let someone tell you what to text your status.",
            "Send your favorite song lyrics.",
            "Talk like a robot until your turn ends.",
            "Pretend to argue with yourself.",
            "Send your WiFi name.",
            "Let the group choose a word you must use in every message for 5 min.",
            "Send your last saved meme.",
            "Pretend you are a king/queen in the group.",
            "Say 'banana' after every sentence for 5 min.",
            "Send a random line from a movie.",
            "Let someone choose an emoji you must use until tomorrow.",
            "Make a fake motivational speech in the chat.",
            "Send your favorite emoji 20 times.",
            "Pretend to be Siri/Google Assistant.",
            "Post a riddle and try to answer it wrong."
        ];

        const chosen = dares[Math.floor(Math.random() * dares.length)];
        sock.sendMessage(msg.key.remoteJid, { text: `🔥 Dare Challenge!\n\n${chosen}` }, { quoted: msg });
    }
};
