// commands/insult.js
module.exports = {
    name: "insult",
    description: "Throw a random insult at someone (for fun only!)",
    execute: async (sock, m) => {
        const insults = [
            "You're like a software update—every time I see you, I just groan and wish I could skip it.",
            "You're proof that even evolution takes a break sometimes.",
            "You're like a cloud. When you disappear, it’s a beautiful day.",
            "If I had a dollar for every brain cell you had, I'd still be broke.",
            "You're like a phone at 1%—completely useless in any situation.",
            "You're living proof that WiFi signals can have more strength than personality.",
            "You're like a math problem nobody can solve—annoying and unnecessary.",
            "You bring people so much joy… when you leave the room.",
            "You’re like a YouTube ad nobody can skip.",
            "You're like a keyboard without the space bar—completely dysfunctional.",
            "You remind me of expired milk—bad smell and nobody wants you around.",
            "You're the reason instructions say 'do not eat' on soap.",
            "You’re like a pencil with no lead—pointless.",
            "Your brain has too many tabs open, and none of them are working.",
            "You're like a glitch in the system—confusing and frustrating.",
            "If stupidity was a sport, you’d be a hall of famer.",
            "You're like a selfie gone wrong—embarrassing to look at.",
            "You’re like dial-up internet—slow, noisy, and outdated.",
            "You're like a spelling mistake in a tattoo—permanent and regrettable.",
            "Your secrets are safe with me. I never even listen when you tell me them.",
            "You're like a microwave with no power—loud, useless, and takes up space.",
            "You're the human version of Monday morning.",
            "You're like a charger that only works when bent at the perfect angle—unreliable.",
            "Your brain is like the Bermuda Triangle—things go in, but they never come back out.",
            "You're like a pop quiz—nobody asked for you and everyone hates you.",
            "You're like Internet Explorer—slow, irrelevant, and forgotten.",
            "You're like a library book—overdue and nobody misses you.",
            "You’re like a joke without a punchline—completely flat.",
            "You're like a door that creaks every time it opens—annoying to everyone nearby.",
            "You're like a puzzle piece from a different set—completely out of place.",
            "You're like a phone with no signal—frustrating and unhelpful.",
            "You’re like a low battery notification—nobody wants to see you.",
            "You're like a sticker that won’t peel off—annoying and useless.",
            "You're like a math teacher who assigns homework on Friday—universally disliked.",
            "You're like a broken remote—nobody can stand dealing with you.",
            "You’re like a traffic jam—nobody likes being stuck with you.",
            "You're like a joke that drags on too long—boring and irritating.",
            "You're like an autocorrect fail—always messing things up.",
            "You're like spam emails—unwanted and ignored.",
            "You’re like a mosquito—small but endlessly annoying.",
            "You're like socks that get lost in the dryer—unnecessary and forgettable.",
            "You're like an unskippable ad—wasting everyone’s time.",
            "You're like a car alarm that won’t stop—frustrating to everyone nearby.",
            "You're like expired gum—no flavor and nobody wants you.",
            "You’re like a broken record—repeating the same nonsense over and over.",
            "You're like a frozen screen—completely stuck and useless.",
            "You're like a game lagging on bad WiFi—frustrating to deal with.",
            "You're like a cracked phone screen—annoying to look at and not worth fixing.",
            "You're like junk mail—cluttering up life with nonsense.",
            "You're like an empty soda can—once useful, now trash.",
            "You're like printer paper jams—universally hated.",
            "You’re like a GPS with no signal—completely lost.",
            "You're like flat soda—disappointing and tasteless.",
            "You're like bad WiFi—slowing everyone down.",
            "You're like a spoiler for a movie—ruining everything for everyone.",
            "You're like a loud sneeze in a quiet room—awkward and unnecessary.",
            "You're like expired batteries—useless and forgotten.",
            "You're like an overplayed song—tired and irritating.",
            "You're like an alarm clock that won’t shut up—hated by everyone.",
            "You're like burnt toast—nobody wants you, but you’re hard to avoid.",
            "You're like a broken pen—taking up space and serving no purpose.",
            "You're like glitter—nobody likes dealing with you and you stick around too long.",
            "You're like a chatty Uber driver—unwanted and annoying.",
            "You're like a computer virus—messing things up for no reason.",
            "You're like background noise—distracting and pointless.",
            "You're like a weak handshake—forgettable and disappointing.",
            "You're like an expired coupon—nobody benefits from you.",
            "You're like loading screens—always slowing everyone down.",
            "You're like a flat tire—stopping progress wherever you go.",
            "You're like an awkward silence—making everyone uncomfortable.",
            "You're like a typo in an important message—embarrassing and frustrating.",
            "You're like a broken elevator—never getting anyone anywhere.",
            "You're like a tangled headphone wire—annoying and useless.",
            "You're like slow cashiers—holding up the line unnecessarily.",
            "You're like bad breath—everyone avoids you but nobody says it out loud.",
            "You're like pop-up ads—nobody asked for you, but you still show up.",
            "You're like an old meme—completely irrelevant.",
            "You're like a frozen drink machine—broken when needed most.",
            "You're like a fly buzzing around—annoying and hard to get rid of.",
            "You're like a loading spinner—always there, never useful.",
            "You're like background apps—draining energy and serving no purpose.",
            "You're like a tangled cord—nobody wants to deal with you.",
            "You're like fake friends—useless and irritating.",
            "You're like an awkward group photo—making everything worse.",
            "You're like a broken promise—disappointing and frustrating.",
            "You're like an echo—repeating nonsense that nobody cares about.",
            "You're like a half-baked cake—never ready and always disappointing.",
            "You're like a default ringtone—boring and easily ignored.",
            "You're like an expired passport—completely useless now.",
            "You're like a paper cut—small but disproportionately annoying.",
            "You're like a rerun of a bad show—nobody wants to watch you again.",
            "You're like a slow elevator—making everyone’s life worse.",
            "You're like cheap earbuds—breaking down when needed most.",
            "You're like a TV static screen—pointless and irritating.",
            "You're like an overcooked noodle—floppy and useless.",
            "You're like a laggy livestream—nobody enjoys dealing with you."
        ];

        const insult = insults[Math.floor(Math.random() * insults.length)];
        await sock.sendMessage(m.chat, { text: insult }, { quoted: m });
    }
};
