// commands/motiv8.js
module.exports = {
    name: "motiv8",
    description: "Send a motivational quote or line to uplift the mood.",
    execute: async (sock, m) => {
        const motivations = [
            "You don’t have to be perfect, you just have to start.",
            "Small steps every day add up to big results.",
            "The fact that you woke up today means you still have a chance.",
            "Your future self will thank you for not giving up today.",
            "Don’t compare your day 1 to someone else’s day 100.",
            "Consistency beats motivation—show up even when it’s hard.",
            "You are more capable than you give yourself credit for.",
            "Great things take time, don’t rush the process.",
            "Discipline will take you where motivation can’t.",
            "Success is built on boring daily habits nobody claps for.",
            "Remember why you started, and let that fuel you.",
            "Even if you fall seven times, stand up eight.",
            "Progress, not perfection—that’s the real goal.",
            "You are one decision away from a completely different life.",
            "Your comfort zone will never let you grow.",
            "Fear is temporary, but regret lasts forever.",
            "Excuses don’t get results—actions do.",
            "Your current struggles are training for your future strength.",
            "Don’t be afraid to fail; be afraid of not trying.",
            "You don’t need to see the whole staircase, just take the first step.",
            "Stay patient. Nothing grows overnight.",
            "Hard work beats talent when talent doesn’t work hard.",
            "Your best teacher is your last mistake.",
            "Don’t limit your challenges, challenge your limits.",
            "The hardest part is starting. Do it now.",
            "Winners are not people who never fail; they’re people who never quit.",
            "Consistency creates miracles that motivation can’t.",
            "Courage is doing what you’re afraid to do.",
            "Work in silence, let success make the noise.",
            "You’re not behind—you’re on your own timeline.",
            "Big goals are just small steps done daily.",
            "The pain you feel now is the strength you’ll feel tomorrow.",
            "Don’t chase perfection; chase progress.",
            "Greatness is not found in comfort zones.",
            "When you want to quit, remember why you started.",
            "Your only competition is who you were yesterday.",
            "You’re stronger than the excuses you keep telling yourself.",
            "Dream big, start small, but start now.",
            "Discipline is the bridge between goals and results.",
            "The more you practice, the luckier you get.",
            "Energy flows where focus goes—stay focused.",
            "You don’t need motivation every day, just consistency.",
            "Struggle now so the future you can relax later.",
            "You can’t have a million-dollar dream with a minimum-wage mindset.",
            "Don’t wait for the right mood; act, and the mood will follow.",
            "It always seems impossible until it’s done.",
            "Push through the bad days; they make the good days worth it.",
            "Every expert was once a beginner.",
            "Motivation gets you started, discipline keeps you going.",
            "You didn’t come this far just to quit.",
            "Good things come to those who hustle.",
            "Success is rented, and rent is due every day.",
            "If you can’t fly, run; if you can’t run, walk; if you can’t walk, crawl—just don’t stop.",
            "You’re building a version of yourself that doesn’t quit.",
            "Don’t let tiredness stop you—rest, then continue.",
            "Excuses will always be there, but opportunity won’t.",
            "Keep your vision bigger than your fears.",
            "The best way to predict the future is to create it.",
            "Don’t let comfort steal your future.",
            "The road to success is always under construction.",
            "Discipline feels hard now but tastes sweet later.",
            "Turn your “I can’t” into “I’ll try.”",
            "Don’t stop when you’re tired, stop when you’re done.",
            "Every day you delay is a day wasted.",
            "If it doesn’t challenge you, it won’t change you.",
            "Your mindset is your superpower—train it.",
            "Action is the antidote to fear.",
            "Don’t watch the clock—make it work for you.",
            "Winners focus on winning, losers focus on winners.",
            "Your dreams don’t work unless you do.",
            "Stop doubting yourself, work hard, and make it happen.",
            "You owe it to yourself to become who you’re capable of being.",
            "Success doesn’t happen overnight; it’s built daily.",
            "Don’t complain about results you didn’t work for.",
            "Excuses sound best to the person who made them.",
            "Be addicted to bettering yourself.",
            "Don’t let the fear of losing stop you from playing the game.",
            "Stay focused—the distraction is just a test.",
            "Your future is created by what you do today, not tomorrow.",
            "The moment you want to quit is the moment you must push through.",
            "Don’t wish for it, work for it.",
            "Nothing worth having comes easy.",
            "Turn your struggles into strength.",
            "Nobody cares about your excuses—results talk.",
            "The secret to success? Start, and don’t stop.",
            "Sacrifice for the future you want.",
            "Every small effort compounds over time.",
            "Focus on progress, not speed.",
            "You’re more powerful than you think.",
            "Failure isn’t the opposite of success—it’s part of it.",
            "Stay hungry, stay foolish.",
            "The grind may hurt now, but quitting hurts forever.",
            "Small consistent efforts beat occasional big efforts.",
            "Show up today, even if you don’t feel like it.",
            "Discipline now, freedom later.",
            "Don’t stop until you’re proud.",
            "Keep going—your future self is cheering for you.",
            "Success doesn’t get easier; you just get stronger.",
            "Start where you are, use what you have, do what you can."
        ];

        const motivation = motivations[Math.floor(Math.random() * motivations.length)];
        await sock.sendMessage(m.chat, { text: motivation }, { quoted: m });
    }
};
