module.exports = {
    name: "riddle",
    description: "Get a random short and fun riddle.",
    execute(sock, msg, args) {
        const riddles = [
            "What has to be broken before you can use it? (Answer: An egg)",
            "I’m tall when I’m young, and I’m short when I’m old. What am I? (Answer: A candle)",
            "The more you take, the more you leave behind. What am I? (Answer: Footsteps)",
            "What has one eye but can’t see? (Answer: A needle)",
            "What gets wetter as it dries? (Answer: A towel)",
            "What belongs to you, but other people use it more than you? (Answer: Your name)",
            "What goes up but never comes down? (Answer: Your age)",
            "The more of me you take, the more you leave behind. What am I? (Answer: Footsteps)",
            "What has a head, a tail, but no body? (Answer: A coin)",
            "What has many keys but can’t open a lock? (Answer: A piano)",
            "What has hands but cannot clap? (Answer: A clock)",
            "What has a neck but no head? (Answer: A bottle)",
            "What gets bigger the more you take away? (Answer: A hole)",
            "What runs but never walks? (Answer: Water)",
            "What has legs but doesn’t walk? (Answer: A table)",
            "What comes down but never goes up? (Answer: Rain)",
            "What kind of band never plays music? (Answer: A rubber band)",
            "What has teeth but doesn’t bite? (Answer: A comb)",
            "What has an endless supply of letters but starts empty? (Answer: A mailbox)",
            "What begins with T, ends with T, and has T in it? (Answer: A teapot)",
            "What has an ear but cannot hear? (Answer: Corn)",
            "The more you take away from me, the bigger I get. What am I? (Answer: A hole)",
            "What has words but never speaks? (Answer: A book)",
            "What has four fingers and a thumb but isn’t alive? (Answer: A glove)",
            "What kind of tree can you carry in your hand? (Answer: A palm tree)",
            "What is full of holes but still holds water? (Answer: A sponge)",
            "What can you catch but not throw? (Answer: A cold)",
            "I fly without wings, I cry without eyes. What am I? (Answer: A cloud)",
            "What goes around the world but stays in a corner? (Answer: A stamp)",
            "What can travel all around the world while staying in one spot? (Answer: A stamp)",
            "What has one head, one foot, and four legs? (Answer: A bed)",
            "What has an end but no beginning? (Answer: A stick)",
            "What has no life but can die? (Answer: A battery)",
            "What gets sharper the more you use it? (Answer: Your brain)",
            "What has many rings but no fingers? (Answer: A tree)",
            "What is always moving but never stops? (Answer: Time)",
            "What has roots that nobody sees? (Answer: A mountain)",
            "What can fill a room but takes up no space? (Answer: Light)",
            "What has a thumb and four fingers but is not alive? (Answer: A glove)",
            "What starts with P, ends with E, and has thousands of letters? (Answer: The Post Office)",
            "What is easy to lift but hard to throw? (Answer: A feather)",
            "What has a bottom at the top? (Answer: A leg)",
            "What comes once in a minute, twice in a moment, but never in a thousand years? (Answer: The letter M)",
            "What can’t talk but will reply when spoken to? (Answer: An echo)",
            "What gets broken if you name it? (Answer: Silence)",
            "What has a ring but no finger? (Answer: A telephone)",
            "What is always in front of you but can’t be seen? (Answer: The future)",
            "What has no beginning, end, or middle? (Answer: A circle)",
            "What runs but never rests? (Answer: A river)"
        ];

        const chosen = riddles[Math.floor(Math.random() * riddles.length)];
        sock.sendMessage(msg.key.remoteJid, { text: `🧩 Riddle Time!\n\n${chosen}` }, { quoted: msg });
    }
};
