module.exports = {
  name: 'rizz',
  async execute(msg) {
    const lines = [
      "Are you Wi-Fi? Because I'm feeling a strong connection.",
      "Do you have a name, or can I call you mine?",
      "You're so hot, my phone overheated just texting you.",
      "If you were a vegetable, you’d be a cutecumber.",
      "I must be a snowflake, because I’ve fallen for you.",
      "Your hand looks heavy—can I hold it for you?",
      "Are you a keyboard? Because you're just my type.",
      "Even my code doesn’t loop over you.",
      "You're so sweet, you could put Hershey’s out of business.",
      "If beauty were time, you’d be an eternity.",
      "Are you French? Because Eiffel for you.",
      "You must be a magician—whenever I look at you, everyone else disappears.",
      "Are you made of copper and tellurium? Because you’re Cu-Te.",
      "You auto-complete me.",
      "If I were a cat, I’d spend all 9 lives with you.",
      "You're so pretty, even my AI had to stop and stare.",
      "Are you an exception? Because I’ve been catching feelings.",
      "My love for you is like a memory leak—uncontrollable and infinite.",
      "If looks could kill, you’d be a weapon of mass destruction.",
      "Are you a cloud function? Because you’re serverless and flawless.",
      "You had me at 'Hello, world'.",
      "I’d debug my entire life for just one date with you.",
      "Are you a 404? Because I can't find anyone like you.",
      "You're the semicolon to my code — you complete me.",
      "Is your name Google? Because you have everything I’m searching for.",
      "You’re my favorite notification.",
      "Are you a Git commit? Because I can’t revert you.",
      "You’re like a high-level API—easy to use and impossible to ignore.",
      "Even my processor slows down when you're around.",
      "You're better than a successful build with no errors.",
      "If this were code, I'd return you every time.",
      "You're a class of your own.",
      "You're my IDEAL type.",
      "Even ChatGPT couldn’t generate someone like you.",
      "You're the light theme in my dark world.",
      "You're the console.log to my heart.",
      "You're my default route.",
      "You're the final boss of beauty.",
      "Are you a pixel? Because you’re looking sharp.",
      "You're the syntax to my structure.",
      "You're the front-end to my back-end.",
      "Are you Figma? Because I want to design my future with you.",
      "If I had a star for every time you brightened my day, I’d own the galaxy.",
      "You're a certified 10... and I'm running out of digits.",
      "I must’ve rolled a natural 20, because you're a critical hit.",
      "You’re the plot twist in my story.",
      "If I were to ask you out, would your answer be the same as the answer to this question?",
      "You're not just a snack, you're the whole buffet.",
      "You're the kind of bug I’d never fix.",
      "My algorithm says you're the one."
    ];
    const rizz = lines[Math.floor(Math.random() * lines.length)];
    msg.reply(rizz);
  }
};
