module.exports = {
    name: "rizz",
    description: "Send a smooth pickup line or rizz someone up.",
    execute(sock, msg, args) {
        const rizzLines = [
            "Are you French? Because *Eiffel* for you.",
            "Do you have a map? I keep getting lost in your eyes.",
            "Are you a bank loan? Because you have my interest.",
            "I must be a snowflake, because I’ve fallen for you.",
            "Do you have WiFi? Because I’m feeling a real connection.",
            "Are you a magician? Because whenever I look at you, everyone else disappears.",
            "Your hand looks heavy — want me to hold it?",
            "Are you Google? Because you’ve got everything I’m searching for.",
            "I must be lost because heaven is a long way from here.",
            "Are you a charger? Because I can’t live without you.",
            "If beauty were a crime, you’d be serving a life sentence.",
            "Are you a keyboard? Because you’re my type.",
            "Are you Australian? Because when I look at you, I feel down under.",
            "I must be a camera, because every time I look at you, I smile.",
            "You must be tired, because you’ve been running through my mind all day.",
            "If you were a vegetable, you’d be a cute-cumber.",
            "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
            "Are you a time traveler? Because I see you in my future.",
            "I must be a beaver, because daaaaam.",
            "Are you the ocean? Because I’m lost at sea in your eyes.",
            "If kisses were snowflakes, I’d send you a blizzard.",
            "Are you a parking ticket? Because you’ve got 'fine' written all over you.",
            "If I could rearrange the alphabet, I’d put U and I together.",
            "Are you a campfire? Because you’re hot and I want s’more.",
            "Do you play soccer? Because you’re a keeper.",
            "Are you made of copper and tellurium? Because you’re Cu-Te.",
            "Do you have a pencil? Because I want to erase your past and write our future.",
            "Are you Netflix? Because I could binge you all night.",
            "Are you gravity? Because you’ve got me falling.",
            "Are you a lock? Because you’re exactly what I’ve been looking for.",
            "If beauty were time, you’d be an eternity.",
            "Are you Wi-Fi? Because I feel the strongest connection with you.",
            "I must be a star, because you make my world shine.",
            "Are you a pillow? Because I want to hug you all night.",
            "Are you coffee? Because you keep me awake.",
            "You must be the square root of -1, because you can’t be real.",
            "Are you Spotify Premium? Because you’re everything I’ve been playing in my head.",
            "You must be a magician, because whenever I look at you, everyone disappears.",
            "Are you lightning? Because you make my heart race.",
            "Are you an artist? Because you just drew me in.",
            "Are you a dictionary? Because you add meaning to my life.",
            "Are you my phone? Because I can’t stop staring at you.",
            "You must be Wi-Fi, because I’m feeling the connection.",
            "Are you a cat? Because you’re purrr-fect.",
            "Are you sunshine? Because you brighten my day.",
            "Are you cake? Because you’re sweet and I want a slice.",
            "Are you an angel? Because I feel blessed when you’re around.",
            "You must be a magnet, because you attract me every time.",
            "Are you a chef? Because you just spiced up my life.",
            "You must be a shooting star, because every time I see you, I make a wish.",
            "Are you ice cream? Because you make everything better.",
            "Are you TikTok? Because I could scroll through you for hours.",
            "Are you the moon? Because you light up my darkest nights.",
            "You must be Bluetooth, because I’m paired with you.",
            "Are you an equation? Because you complete my function.",
            "Are you my dream? Because I don’t want to wake up.",
            "You must be a charger, because I die without you.",
            "Are you a candle? Because you light up my world.",
            "Are you air? Because I can’t live without you.",
            "You must be my glasses, because I can finally see clearly with you.",
            "Are you fast food? Because I’m lovin’ it.",
            "You must be a dictionary — you give meaning to my life.",
            "Are you a sunrise? Because you make everything brighter.",
            "You must be a painting — priceless and beautiful.",
            "Are you an app? Because you’ve got me hooked.",
            "Are you a melody? Because you’re stuck in my head.",
            "You must be summer, because you make everything warm.",
            "Are you candy? Because you’re too sweet to handle.",
            "You must be starlight, because you shine from far away.",
            "Are you my favorite song? Because I can’t get you out of my head.",
            "Are you chocolate? Because you melt my heart.",
            "You must be WiFi — I’m connected to you.",
            "Are you fire? Because you’re too hot to handle.",
            "You must be my shadow, because I can’t escape you.",
            "Are you a book? Because every page about you is amazing.",
            "Are you pizza? Because even when you’re bad, you’re still good.",
            "You must be gold, because you’re worth everything.",
            "Are you thunder? Because you make my heart beat faster.",
            "You must be perfume, because I can’t stop smelling you.",
            "Are you rain? Because you make everything better.",
            "Are you a blanket? Because I want to wrap myself in you.",
            "Are you WiFi? Because I feel empty without you.",
            "Are you YouTube? Because I can’t skip you.",
            "You must be rare, because I can’t find anyone like you.",
            "Are you sugar? Because you’re too sweet.",
            "You must be a planet, because my world revolves around you.",
            "Are you ketchup? Because you complete my fries.",
            "Are you my phone’s battery? Because you’re running my life.",
            "You must be glue, because I’m stuck on you.",
            "Are you Christmas? Because you make everything special.",
            "You must be the alphabet, because you’re all I need.",
            "Are you an astronaut? Because you just rocketed my heart.",
            "Are you butter? Because you make everything smooth.",
            "You must be rainbows, because you make life colorful.",
            "Are you Wi-Fi? Because when you’re gone, nothing works.",
            "Are you a diamond? Because you shine under pressure.",
            "You must be my favorite movie, because I could watch you forever.",
            "Are you electricity? Because you shock me every time.",
            "Are you April? Because you just fooled me into falling again."
        ];

        const chosen = rizzLines[Math.floor(Math.random() * rizzLines.length)];
        sock.sendMessage(msg.key.remoteJid, { text: `💘 Rizz Activated!\n\n${chosen}` }, { quoted: msg });
    }
};
