module.exports = {
  name: 'roast',
  async execute(msg) {
    const burns = [
      "You're like a cloud. When you disappear, it's a beautiful day.",
      "Your secrets are always safe with me. I never even listen when you tell me them.",
      "You bring everyone so much joy… when you leave the room.",
      "You're not stupid; you just have bad luck thinking.",
      "Your face makes onions cry.",
      "You're like a software update. Whenever I see you, I think, 'Not now.'",
      "You're the reason shampoo bottles have instructions.",
      "You're like a broken pencil—pointless.",
      "You're the human version of a participation trophy.",
      "You're slower than dial-up internet.",
      "You have something on your chin... no, the third one down.",
      "You're not ugly—you’re just… aesthetically challenged.",
      "You're so dense, black holes get jealous.",
      "If I wanted to hear from someone irrelevant, I'd start talking to my old phone.",
      "You're like a puzzle with half the pieces missing.",
      "You're the kind of person that makes happy meals sad.",
      "You're the reason I prefer AI friends.",
      "You're so fake, even Barbie feels real next to you.",
      "You're a few fries short of a happy meal.",
      "You're so old, your birth certificate expired.",
      "You're like expired milk—everyone avoids you.",
      "You bring everyone down to your level—then beat them with experience.",
      "You have something on your face… oh wait, that’s just your face.",
      "You're not lazy. You're just in energy-saving mode… permanently.",
      "You're so weird, even your imaginary friends left you.",
      "You're the type who would trip over a wireless signal.",
      "You're so dry, not even a cactus could survive around you.",
      "You're like a password with no characters—useless.",
      "You're so annoying, even Siri ignores you.",
      "You're not bad at coding… you're worse.",
      "You're the main reason evolution isn't real-time.",
      "You're like JavaScript hoisting—confusing and unpredictable.",
      "You're the human version of a corrupted file.",
      "You're not even worth a try-catch block.",
      "You're like a semicolon at the end of a JSON file—unwanted.",
      "Your logic is so flawed, even NaN makes more sense.",
      "You're the null of my life.",
      "You're so slow, setTimeout() finishes before you respond.",
      "You're so dumb, even ChatGPT refuses to generate your response.",
      "You're a bug in everyone's life.",
      "You're so ugly, when you look in the mirror, your reflection logs out.",
      "You belong in the trash folder.",
      "You were born at a very young age — and it shows.",
      "You’re proof that natural selection isn’t perfect.",
      "You’re like a try block without a catch — useless.",
      "You're like an 'if' statement that never runs.",
      "You’re the exception, not the rule. And not in a good way.",
      "You're what happens when logic takes a vacation.",
      "You're the clown of a one-man circus.",
      "You're not even the main character in your own story."
    ];
    const roast = burns[Math.floor(Math.random() * burns.length)];
    msg.reply(roast);
  }
};
