module.exports = {
    name: "roast",
    description: "Throw a random roast at someone for fun.",
    execute(sock, msg, args) {
        const roasts = [
            "You bring everyone so much joy… when you leave the room.",
            "You have something on your chin… no, the third one down.",
            "You’re like a cloud. When you disappear, it’s a beautiful day.",
            "You bring people together — just like a traffic jam.",
            "You have something nobody else has… bad luck and bad jokes.",
            "You look like a 'before' picture.",
            "You bring balance to life: zero talent, zero style, zero sense.",
            "You bring a lot to the table… like crumbs.",
            "You look like the reason shampoo has instructions.",
            "You bring people hope… that they’re not as bad as you.",
            "You’re like a software update. Whenever I see you, I think: 'Do I really need this?'",
            "You bring light wherever you go… because you block the sun.",
            "You must be a magician — every time you talk, everyone disappears.",
            "You’re like Monday mornings: nobody likes you, but we’re stuck with you.",
            "You’re proof that even evolution takes breaks.",
            "You bring so little to the table, even salt feels useful.",
            "You have two brain cells left, and they’re arguing.",
            "You bring people together… because they all roast you instead.",
            "You look like WiFi with no signal.",
            "You’re like a cloud storage plan — limited and disappointing.",
            "You bring nothing to the group but typing noise.",
            "You must be the human version of a typo.",
            "You bring the energy of a phone at 1% with no charger.",
            "You’re like a math problem — complicated and unnecessary.",
            "You bring nothing but buffering vibes.",
            "You look like the aftertaste of medicine.",
            "You’re like a password nobody remembers.",
            "You must have been born on a highway — most accidents happen there.",
            "You bring less to life than an expired coupon.",
            "You’re like a low-battery warning: annoying and constant.",
            "You bring nothing but lag to conversations.",
            "You look like someone who claps when the plane lands.",
            "You’re the reason even mute buttons exist.",
            "You’re like a cloud subscription — expensive and useless.",
            "You look like free WiFi with no internet.",
            "You’re like a dictionary — full of words, none useful.",
            "You must be a parking ticket, because you’ve got 'fine' written nowhere.",
            "You look like a 404 error.",
            "You’re like a software bug — nobody asked for you, but here you are.",
            "You bring the same vibes as a printer error: pointless frustration.",
            "You’re like a selfie from the wrong angle — tragic.",
            "You must be made of copper and tellurium, because you’re Cu-Te… oh wait, no, you’re just toxic.",
            "You bring less to the party than a flat soda.",
            "You’re like a knock-off phone charger — you look okay, but nobody trusts you.",
            "You must be Bluetooth: always searching but never connecting.",
            "You’re like autocorrect — wrong every time.",
            "You bring people joy by muting notifications.",
            "You’re like a slow elevator — everyone wishes they took the stairs.",
            "You look like the last slice nobody wants.",
            "You bring people patience… by testing it.",
            "You’re like a screenshot — nobody asked, but you’re still here.",
            "You’re like an expired meme — no one laughs anymore.",
            "You bring no heat but somehow stay roasting.",
            "You must be a password hint — confusing and useless.",
            "You bring nothing but unread messages.",
            "You’re like a badly written joke — nobody gets you.",
            "You’re the reason shampoo has safety caps.",
            "You’re like a loading bar stuck at 99%.",
            "You bring disappointment like a vending machine eating money.",
            "You look like someone’s backup plan’s backup plan.",
            "You’re like Internet Explorer — nobody uses you anymore.",
            "You bring about as much fun as a dentist appointment.",
            "You’re like an unskippable ad on YouTube.",
            "You look like a potato that gave up.",
            "You’re like a broken pencil — pointless.",
            "You’re like a traffic light stuck on red.",
            "You bring the same vibes as lag in online games.",
            "You’re like background noise: annoying and ignored.",
            "You look like the reason group projects fail.",
            "You’re like a frozen screen — nothing’s working here.",
            "You must be a push notification — always irrelevant.",
            "You bring boredom to new heights.",
            "You look like you failed captcha tests.",
            "You’re like an unsaved document — useless when gone.",
            "You’re like the slowest WiFi ever — frustrating and unreliable.",
            "You look like a loading spinner without end.",
            "You’re like spam mail — nobody wants you.",
            "You bring the energy of a skipped playlist song.",
            "You’re like a fake friend request.",
            "You look like a badly drawn emoji.",
            "You’re like a dying light bulb — flickering and annoying.",
            "You bring no signal, just static.",
            "You’re like a flat tire — stopping everything for no reason.",
            "You’re like a rejected app idea.",
            "You look like someone pressed shuffle on evolution.",
            "You’re like the worst riddle — no answer and no fun.",
            "You bring nothing but lagging vibes.",
            "You’re like a phone without storage — can’t handle anything.",
            "You’re like a sequel nobody asked for.",
            "You look like a spelling mistake in permanent ink.",
            "You’re like a knock-knock joke with no punchline.",
            "You bring as much joy as a broken charger.",
            "You’re like a group chat muted forever.",
            "You look like the reason pencils have erasers.",
            "You’re like daylight savings — confusing and unnecessary.",
            "You’re like an offline Netflix screen.",
            "You’re like expired milk — nobody wants you around.",
            "You look like the 1-star review of life.",
            "You bring the same thrill as a blank email notification."
        ];

        const chosen = roasts[Math.floor(Math.random() * roasts.length)];
        sock.sendMessage(msg.key.remoteJid, { text: `🔥 Roast Time!\n\n${chosen}` }, { quoted: msg });
    }
};
