const secretLines = [
  "Someone in your contact list secretly checks your profile picture more than once a day.",
  "You once walked past your soulmate and didn’t even know it.",
  "At least one of your friends has saved an embarrassing photo of you without your knowledge.",
  "Someone you know has rehearsed what they would say if you asked them out.",
  "A person you least expect has dreamt about you recently.",
  "One of your friends once lied to protect your feelings.",
  "Someone saved your number with a funny nickname you’d never guess.",
  "There’s a person who always notices when you come online but never messages first.",
  "One of your old classmates secretly admired you but never spoke about it.",
  "A secret admirer has shown your picture to their close friend before.",
  "Someone checks your statuses hoping to catch a hidden message.",
  "One of your group chats talks about you when you’re not online.",
  "Someone once deleted a message meant for you but regretted it later.",
  "A person you know has a screenshot of one of your old posts.",
  "Your smile has been the topic of conversation in a private chat before.",
  "Someone silently feels jealous when they see your updates.",
  "A person you think barely notices you has thought of you today.",
  "At least one of your friends once borrowed your stuff and never returned it.",
  "Someone has practiced your name with an emoji in their notes.",
  "Your vibe has made someone secretly change how they dress.",
  "Someone looks at your typing bubbles and wishes you’d finish faster.",
  "A person you know once cried while thinking about you.",
  "There’s a crush in your circle who hides it behind jokes.",
  "Someone has pretended to be busy just to avoid revealing their excitement around you.",
  "You’ve been the subject of a late-night conversation you didn’t know about.",
  "Someone once retyped a message to you five times before hitting send.",
  "A close friend has kept a big secret from you for years.",
  "Someone in your life has asked about you more times than you imagine.",
  "Your laugh has been described to someone else as ‘the best.’",
  "A person you know checks your last seen before they go to bed.",
  "Someone has secretly added your name with a heart in their phone.",
  "There’s a person who avoids your eyes because they feel shy around you.",
  "One of your group members muted you just because they couldn’t stop checking your texts.",
  "Someone has saved your birthday even if you never told them directly.",
  "At least one of your teachers or bosses secretly admired your confidence.",
  "Someone once posted something indirectly aimed at you.",
  "Your online habits have been noticed more than you think.",
  "A friend sometimes lies about small things just to look cooler in front of you.",
  "Someone uses your DP as their example of ‘nice aesthetic.’",
  "One of your crushes told someone else about their feelings, not you.",
  "There’s a person who replays your voice notes secretly.",
  "Someone you least expect once imagined holding your hand.",
  "At least one of your selfies lives in someone else’s gallery.",
  "Someone has watched your story on repeat before.",
  "A person sometimes uses your jokes when chatting with others.",
  "Someone pretended not to see your message but read it multiple times.",
  "At least one of your photos has been zoomed in and stared at longer than you know.",
  "There’s a person who typed a love confession to you but deleted it.",
  "Someone has bragged about knowing you to someone else.",
  "One of your followers saved your post offline.",
  "A friend secretly thinks you’d make a great partner.",
  "Someone once smiled at their phone because of your message.",
  "At least one person has you on their secret crush list.",
  "Someone gets low-key jealous when they see your tagged photos.",
  "One of your contacts checks your online status at odd hours.",
  "Someone has shown your photo to a sibling or cousin.",
  "A person once lied about being busy just to seem cool to you.",
  "There’s someone who typed your name with hearts in their diary.",
  "Someone hides their happiness when you text them.",
  "Your silence has once made someone feel very restless.",
  "Someone remembers the exact first time you texted them.",
  "At least one of your secrets is known by someone you never told.",
  "Someone imagines you in their future without you knowing.",
  "A friend sometimes competes with you secretly.",
  "Your hairstyle once inspired someone else to copy you.",
  "Someone you don’t talk to much wants badly to text you.",
  "At least one person stalks your posts but never likes them.",
  "Someone has googled your name out of curiosity.",
  "A friend keeps screenshots of your chats hidden.",
  "Someone smiles when they read your old messages.",
  "Someone in your circle hides a big crush on you.",
  "A person waits for you to post just to interact.",
  "Someone has saved your nickname as their Wi-Fi password.",
  "Someone checks your bio to see if it changes.",
  "There’s a person who always notices when you delete a post.",
  "Someone brags about your talent when you’re not there.",
  "At least one person has drawn a doodle of you.",
  "Someone uses your favorite emoji because of you.",
  "Your DP once made someone blush in real life.",
  "Someone holds back compliments because they fear it’s too obvious.",
  "Someone once dreamed of confessing to you but woke up.",
  "At least one of your friends thinks of you as their inspiration.",
  "Someone feels nervous every time you say their name.",
  "Your number is saved under a funny name in someone’s phone.",
  "A person once deleted a picture because you didn’t like it.",
  "Someone thinks of you as their ‘lucky charm.’",
  "At least one friend wishes they could be more like you.",
  "Your old posts are checked more than you imagine.",
  "Someone feels secretly happy when you tag them.",
  "Your typing style has been copied by someone.",
  "Someone once wished you’d join their group chat permanently.",
  "A person checks if you’re awake based on your activity.",
  "Someone has written about you in their journal.",
  "At least one contact daydreams about you often.",
  "Someone is waiting for you to text them right now.",
  "A person avoids admitting how much they admire you.",
  "Someone once replayed your call multiple times.",
  "Your laugh is a ringtone in someone’s head.",
  "Someone is secretly grateful you exist in their life."
];

module.exports = {
  name: "secret",
  description: "Reveals a random funny or mysterious secret.",
  execute(sock, m) {
    const line = secretLines[Math.floor(Math.random() * secretLines.length)];
    sock.sendMessage(m.chat, { text: line }, { quoted: m });
  }
};

