const secrets = [
  "I once cried watching cartoons.",
  "I stalk this group more than I chat.",
  "I used to fake poor network to ignore people.",
  "I screenshot chats I find funny.",
  "I skip voice notes that are longer than 10 seconds.",
  "I fake reply with '😂' even when it’s not funny.",
  "Sometimes I ghost and feel no guilt.",
  "I check everyone's status, but never post mine.",
  "I act like I don't care, but I really do.",
  "I’ve had a crush on someone in this group.",
  "I once muted someone but still read their messages.",
  "I’ve sent a risky text and deleted it immediately.",
  "I sometimes argue just to win, not cause I’m right.",
  "I talk to myself and win arguments too.",
  "I read messages and pretend I didn’t.",
  "I’ve lied about my phone dying just to log off.",
  "I blocked someone once — just for peace.",
  "I’ve pretended to forget just to avoid awkwardness.",
  "I once reacted to a meme with the wrong emoji.",
  "I laugh in real life at chats but don’t reply.",
  "I skip voice notes unless it’s from a crush.",
  "I’ve played both sides in an argument before.",
  "I sometimes stalk mutual friends out of boredom.",
  "I check WhatsApp first thing in the morning.",
  "I’ve left groups just to see who notices.",
  "I once pretended my mic wasn’t working.",
  "I pretend to be offline to avoid small talk.",
  "I once spammed a group just to revive it.",
  "I lowkey judge people by their typing speed.",
  "I once ignored someone for 3 days then replied 'sorry, busy.'",
  "I always look at who viewed my story first.",
  "I read deleted messages using notification previews.",
  "I once used someone else’s meme and claimed it.",
  "I’ve deleted chats out of anxiety.",
  "I still check chats I muted.",
  "I act cool in groups but I’m shy in real life.",
  "I panic when someone says 'we need to talk'.",
  "I sometimes forget I even sent a message.",
  "I’ve sent a risky meme and waited nervously.",
  "I fake being surprised when I already know the tea.",
  "I’ve joined a group and muted it instantly.",
  "I reply 'lol' when I’m confused.",
  "I once made a fake excuse to leave a group call.",
  "I download statuses I don’t even like.",
  "I read old chats just for nostalgia.",
  "I once liked someone’s story by mistake.",
  "I pretend I’m typing just to stall.",
  "I ghosted and then came back like nothing happened.",
  "I once asked a friend to view my status first."
];

module.exports = {
  name: 'secret',
  execute(msg) {
    const random = secrets[Math.floor(Math.random() * secrets.length)];
    msg.reply(`🤫 Secret confession:\n${random}`);
  }
};
