module.exports = {
    name: "trivia",
    description: "Get a random trivia question.",
    execute(sock, msg, args) {
        const trivia = [
            "What is the capital of France? (Answer: Paris)",
            "Who painted the Mona Lisa? (Answer: Leonardo da Vinci)",
            "What is the smallest planet in our solar system? (Answer: Mercury)",
            "What year did World War II end? (Answer: 1945)",
            "What is the fastest land animal? (Answer: Cheetah)",
            "What is the largest ocean on Earth? (Answer: Pacific Ocean)",
            "Who wrote 'Romeo and Juliet'? (Answer: William Shakespeare)",
            "What is the hardest natural substance on Earth? (Answer: Diamond)",
            "Which country is known as the Land of the Rising Sun? (Answer: Japan)",
            "What is the boiling point of water in Celsius? (Answer: 100°C)",
            "Who was the first man to step on the moon? (Answer: Neil Armstrong)",
            "What gas do humans need to survive? (Answer: Oxygen)",
            "Which planet is known as the Red Planet? (Answer: Mars)",
            "What is the largest mammal? (Answer: Blue Whale)",
            "What is the square root of 64? (Answer: 8)",
            "Which continent is the Sahara Desert located in? (Answer: Africa)",
            "Who discovered gravity under an apple tree? (Answer: Isaac Newton)",
            "What is the longest river in the world? (Answer: Nile River)",
            "What is the national sport of Japan? (Answer: Sumo wrestling)",
            "Which animal is known as the King of the Jungle? (Answer: Lion)",
            "What is the chemical symbol for gold? (Answer: Au)",
            "What is the capital city of Italy? (Answer: Rome)",
            "What is the main language spoken in Brazil? (Answer: Portuguese)",
            "How many continents are there on Earth? (Answer: Seven)",
            "What is the freezing point of water in Celsius? (Answer: 0°C)",
            "What is the tallest mountain in the world? (Answer: Mount Everest)",
            "What is the main ingredient in guacamole? (Answer: Avocado)",
            "Which organ pumps blood through the human body? (Answer: The heart)",
            "What year did the Titanic sink? (Answer: 1912)",
            "Which is the only mammal capable of true flight? (Answer: Bat)",
            "What is the capital of Egypt? (Answer: Cairo)",
            "What is the largest desert on Earth? (Answer: Antarctica)",
            "How many sides does a hexagon have? (Answer: Six)",
            "Which famous scientist developed the theory of relativity? (Answer: Albert Einstein)",
            "What is the capital city of Canada? (Answer: Ottawa)",
            "What type of blood can be donated to anyone? (Answer: O negative)",
            "What is the currency of the United Kingdom? (Answer: Pound sterling)",
            "Which bird is a symbol of peace? (Answer: Dove)",
            "Which planet is closest to the sun? (Answer: Mercury)",
            "What is the tallest animal on Earth? (Answer: Giraffe)",
            "How many players are on a soccer team? (Answer: 11)",
            "What element does 'O' stand for on the periodic table? (Answer: Oxygen)",
            "Who invented the lightbulb? (Answer: Thomas Edison)",
            "What is the capital of Australia? (Answer: Canberra)",
            "Which is the largest internal organ in the human body? (Answer: Liver)",
            "What country is famous for the Great Wall? (Answer: China)",
            "What is the chemical formula for water? (Answer: H₂O)",
            "Which country invented pizza? (Answer: Italy)",
            "What planet has rings around it? (Answer: Saturn)"
        ];

        const chosen = trivia[Math.floor(Math.random() * trivia.length)];
        sock.sendMessage(msg.key.remoteJid, { text: `🎯 Trivia Time!\n\n${chosen}` }, { quoted: msg });
    }
};
