module.exports = {
    name: "truth",
    description: "Answer a random truth question, fun for games.",
    execute(sock, msg, args) {
        const truths = [
            "What is the biggest secret you’ve kept from your parents?",
            "Have you ever lied to get out of trouble?",
            "Who was your first crush and do you still like them?",
            "What is the most embarrassing thing you’ve ever done in public?",
            "What’s the weirdest dream you’ve ever had?",
            "Have you ever stalked someone on social media?",
            "What’s the worst excuse you’ve ever used?",
            "Have you ever broken something and blamed someone else?",
            "What’s your guilty pleasure song?",
            "If you could erase one memory, what would it be?",
            "What’s the biggest lie you’ve ever told a friend?",
            "Have you ever cheated in a test or exam?",
            "What is the most childish thing you still do?",
            "What’s one thing you would never tell your best friend?",
            "What’s the most awkward date you’ve ever been on?",
            "Have you ever pretended to like a gift?",
            "What’s your most ridiculous fear?",
            "Have you ever laughed at the wrong moment?",
            "What’s the worst habit you have?",
            "Who is the most annoying person you know?",
            "What’s the most trouble you’ve been in at school?",
            "Have you ever eavesdropped on someone’s conversation?",
            "What’s one thing you’ve done that you still regret?",
            "Who was the last person you lied to?",
            "What’s the weirdest thing you’ve ever eaten?",
            "Have you ever been caught sneaking out?",
            "What’s your biggest insecurity?",
            "Have you ever cried during a movie? Which one?",
            "Who in this group would you not want to be stranded with?",
            "What’s the longest you’ve gone without showering?",
            "What’s your biggest secret crush?",
            "Have you ever been caught telling a lie?",
            "What’s the dumbest way you’ve hurt yourself?",
            "Who in this group would you date if you had to?",
            "What’s the most embarrassing nickname you’ve had?",
            "What’s the strangest dream you’ve ever had?",
            "Have you ever read someone else’s messages without them knowing?",
            "What’s your most embarrassing childhood memory?",
            "Who was your first kiss? Was it good?",
            "Have you ever skipped school without permission?",
            "What’s the weirdest rumor you’ve heard about yourself?",
            "What’s one thing you’d change about your past?",
            "What’s the most money you’ve ever wasted?",
            "Have you ever embarrassed yourself in front of your crush?",
            "What’s the biggest risk you’ve ever taken?",
            "What’s your wildest fantasy?",
            "Have you ever been rejected? How did it feel?",
            "Who was your favorite teacher and why?",
            "What’s one lie you’ve told recently?",
            "What’s the worst haircut you’ve ever had?",
            "What’s the most expensive thing you’ve broken?",
            "What’s the funniest thing that’s ever happened to you?",
            "Have you ever peed in a pool?",
            "What’s one food you could eat forever?",
            "What’s one habit you want to quit?",
            "What’s the longest you’ve stayed up?",
            "Have you ever sent a text to the wrong person?",
            "Who’s the last person you stalked on social media?",
            "What’s the meanest thing you’ve ever said to someone?",
            "What’s your most awkward social moment?",
            "Have you ever lied about your age?",
            "What’s the worst advice you’ve ever given?",
            "Have you ever ruined a surprise party?",
            "What’s the most embarrassing thing you’ve Googled?",
            "Have you ever fallen asleep in class?",
            "What’s the most boring date you’ve been on?",
            "Have you ever farted in public and blamed someone else?",
            "What’s the weirdest crush you’ve ever had?",
            "What’s the biggest secret you’ve kept from your best friend?",
            "Have you ever lied during Truth or Dare?",
            "What’s one thing you’d never tell your parents?",
            "What’s the dumbest rumor you believed?",
            "Who here do you think gossips the most?",
            "What’s the weirdest thing you’ve done when alone?",
            "Have you ever ghosted someone?",
            "What’s the worst grade you’ve ever gotten?",
            "Have you ever been caught cheating?",
            "What’s the longest time you’ve spent without your phone?",
            "What’s the most awkward compliment you’ve ever gotten?",
            "What’s the worst present you’ve ever received?",
            "Have you ever told someone’s secret?",
            "What’s the silliest thing you’re afraid of?",
            "What’s one thing you regret buying?",
            "Have you ever laughed so hard you cried?",
            "What’s the weirdest lie you’ve told?",
            "Who was your childhood celebrity crush?",
            "What’s the most awkward text you’ve sent?",
            "Have you ever cried in public?",
            "What’s your weirdest hidden talent?",
            "What’s the most random thing in your room?",
            "What’s the most embarrassing thing in your search history?",
            "Have you ever embarrassed yourself on stage?",
            "What’s the worst excuse you’ve ever made?",
            "What’s the most awkward family dinner you’ve had?",
            "What’s the strangest thing you’ve done for money?",
            "What’s your most embarrassing social media post?",
            "Who’s the last person you unfollowed?",
            "What’s the funniest lie you’ve ever told?",
            "What’s the weirdest superstition you believe?",
            "What’s one thing you’re glad your parents don’t know?",
            "What’s the longest time you’ve ignored someone’s message?",
            "What’s one thing you’ve done that shocked your friends?",
            "What’s your biggest regret so far?",
            "What’s the weirdest place you’ve ever fallen asleep?"
        ];

        const chosen = truths[Math.floor(Math.random() * truths.length)];
        sock.sendMessage(msg.key.remoteJid, { text: `❓ Truth Time!\n\n${chosen}` }, { quoted: msg });
    }
};
