module.exports = {
    name: 'rizz',
    description: 'Smooth or funny pickup lines',
    async execute(sock, message, args, { from }) {
        const pickupLines = [
            "Are you a magician? Because whenever I look at you, everyone else disappears.",
            "Do you have a name, or can I call you mine?",
            "Is your name Google? Because you have everything I've been searching for.",
            "Do you believe in love at first sight, or should I walk by again?",
            "If you were a vegetable, you'd be a cute-cumber!",
            "Are you a parking ticket? Because you've got FINE written all over you.",
            "I must be a snowflake because I've fallen for you.",
            "Do you have a map? I keep getting lost in your eyes.",
            "Are you an alien? Because you just abducted my heart.",
            "Is your dad a boxer? Because you're a knockout!",
            "If you were a fruit, you'd be a fineapple.",
            "Are you a camera? Because every time I look at you, I smile.",
            "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
            "If you were a transformer, you'd be Optimus Fine.",
            "Are you a time traveler? Because I see you in my future.",
            "Do you have a sunburn, or are you always this hot?",
            "If you were a library book, I'd check you out.",
            "Are you a beaver? Because daaaaam.",
            "Do you have a pencil? Because I want to erase your past and write our future.",
            "If you were a burger at McDonald's, you'd be the McGorgeous.",
            "Are you a volcano? Because I lava you.",
            "Do you have a name, or can I call you mine?",
            "If you were a cat, you'd purr-fect.",
            "Are you a light switch? Because you turn me on.",
            "Do you have a twin? Because I see double the beauty.",
            "If you were a flower, you'd be a damnn-delion.",
            "Are you a bank loan? Because you have my interest.",
            "Do you have a mirror in your pocket? Because I can see myself in your pants.",
            "If you were a triangle, you'd be acute one.",
            "Are you a dictionary? Because you add meaning to my life.",
            "Do you have a license? Because you're driving me crazy.",
            "If you were a star, you'd be the brightest one.",
            "Are you a thief? Because you stole my heart.",
            "Do you have a map? I keep getting lost in your eyes.",
            "If you were a song, you'd be the best track on the album.",
            "Are you a snowstorm? Because you're making my heart race.",
            "Do you have a name, or can I call you mine?",
            "If you were a painting, you'd be a masterpiece.",
            "Are you a firework? Because you light up my life.",
            "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
            "If you were a book, you'd be a bestseller.",
            "Are you a volcano? Because I lava you.",
            "Do you have a sunburn, or are you always this hot?",
            "If you were a flower, you'd be a rose.",
            "Are you a camera? Because every time I look at you, I smile.",
            "Do you have a twin? Because I see double the beauty.",
            "If you were a cat, you'd be purr-fect.",
            "Are you a light switch? Because you turn me on.",
            "Do you have a mirror in your pocket? Because I can see myself in your pants.",
            "If you were a triangle, you'd be acute one.",
            "Are you a dictionary? Because you add meaning to my life."
        ];
        
        const randomLine = pickupLines[Math.floor(Math.random() * pickupLines.length)];
        await sock.sendMessage(from, { text: `🌟 ${randomLine}` }, { quoted: message });
    }
};
