module.exports = {
    name: 'roast',
    description: 'Playfully roast your friends',
    async execute(sock, message, args, { from }) {
        const roasts = [
            "You're like a cloud. When you disappear, it's a beautiful day.",
            "I'm not saying you're ugly, but if you were a scarecrow, birds would avoid your field out of pity.",
            "You're not stupid; you just have bad luck when it comes to thinking.",
            "If I had a face like yours, I'd sue my parents.",
            "You're like a software update. Whenever I see you, I think 'Not now'.",
            "You're like a penny. Two-faced and not worth much.",
            "If laughter is the best medicine, your face must be curing the world.",
            "You're like a candle in the wind - easily blown out and forgotten.",
            "I'd agree with you, but then we'd both be wrong.",
            "You're like a broken pencil. Pointless.",
            "You're not completely useless. You can always serve as a bad example.",
            "If brains were dynamite, you wouldn't have enough to blow your nose.",
            "You're like a cloud. When you disappear, it's a beautiful day.",
            "You're like a software update. Whenever I see you, I think 'Not now'.",
            "You're like a penny. Two-faced and not worth much.",
            "If laughter is the best medicine, your face must be curing the world.",
            "You're like a candle in the wind - easily blown out and forgotten.",
            "I'd agree with you, but then we'd both be wrong.",
            "You're like a broken pencil. Pointless.",
            "You're not completely useless. You can always serve as a bad example.",
            "If brains were dynamite, you wouldn't have enough to blow your nose.",
            "You're like a cloud. When you disappear, it's a beautiful day.",
            "You're like a software update. Whenever I see you, I think 'Not now'.",
            "You're like a penny. Two-faced and not worth much.",
            "If laughter is the best medicine, your face must be curing the world.",
            "You're like a candle in the wind - easily blown out and forgotten.",
            "I'd agree with you, but then we'd both be wrong.",
            "You're like a broken pencil. Pointless.",
            "You're not completely useless. You can always serve as a bad example.",
            "If brains were dynamite, you wouldn't have enough to blow your nose.",
            "You're like a cloud. When you disappear, it's a beautiful day.",
            "You're like a software update. Whenever I see you, I think 'Not now'.",
            "You're like a penny. Two-faced and not worth much.",
            "If laughter is the best medicine, your face must be curing the world.",
            "You're like a candle in the wind - easily blown out and forgotten.",
            "I'd agree with you, but then we'd both be wrong.",
            "You're like a broken pencil. Pointless.",
            "You're not completely useless. You can always serve as a bad example.",
            "If brains were dynamite, you wouldn't have enough to blow your nose.",
            "You're like a cloud. When you disappear, it's a beautiful day.",
            "You're like a software update. Whenever I see you, I think 'Not now'.",
            "You're like a penny. Two-faced and not worth much.",
            "If laughter is the best medicine, your face must be curing the world.",
            "You're like a candle in the wind - easily blown out and forgotten.",
            "I'd agree with you, but then we'd both be wrong.",
            "You're like a broken pencil. Pointless.",
            "You're not completely useless. You can always serve as a bad example.",
            "If brains were dynamite, you wouldn't have enough to blow your nose."
        ];
        
        const randomRoast = roasts[Math.floor(Math.random() * roasts.length)];
        await sock.sendMessage(from, { text: `🔥 ${randomRoast}` }, { quoted: message });
    }
};
