module.exports = {
    name: 'trivia',
    description: 'Quiz questions to test knowledge',
    async execute(sock, message, args, { from }) {
        const triviaQuestions = [
            { question: "What is the capital of France?", answer: "Paris" },
            { question: "Which planet is known as the Red Planet?", answer: "Mars" },
            { question: "What is the largest mammal in the world?", answer: "Blue whale" },
            { question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci" },
            { question: "What is the smallest country in the world?", answer: "Vatican City" },
            { question: "Which element has the chemical symbol 'O'?", answer: "Oxygen" },
            { question: "What is the longest river in the world?", answer: "Nile" },
            { question: "Who wrote 'Romeo and Juliet'?", answer: "William Shakespeare" },
            { question: "What is the hardest natural substance on Earth?", answer: "Diamond" },
            { question: "Which ocean is the largest?", answer: "Pacific Ocean" },
            { question: "What is the capital of Japan?", answer: "Tokyo" },
            { question: "Who developed the theory of relativity?", answer: "Albert Einstein" },
            { question: "What is the main component of the Sun?", answer: "Hydrogen" },
            { question: "Which country is home to the kangaroo?", answer: "Australia" },
            { question: "What is the smallest bone in the human body?", answer: "Stapes" },
            { question: "Who wrote 'Pride and Prejudice'?", answer: "Jane Austen" },
            { question: "What is the largest desert in the world?", answer: "Antarctica" },
            { question: "Which planet has the most moons?", answer: "Saturn" },
            { question: "What is the capital of Canada?", answer: "Ottawa" },
            { question: "Who invented the telephone?", answer: "Alexander Graham Bell" },
            { question: "What is the largest continent by area?", answer: "Asia" },
            { question: "Which gas makes up most of Earth's atmosphere?", answer: "Nitrogen" },
            { question: "What is the capital of Australia?", answer: "Canberra" },
            { question: "Who painted 'Starry Night'?", answer: "Vincent van Gogh" },
            { question: "What is the largest organ in the human body?", answer: "Skin" },
            { question: "Which country is known as the Land of the Rising Sun?", answer: "Japan" },
            { question: "What is the smallest planet in our solar system?", answer: "Mercury" },
            { question: "Who wrote 'The Great Gatsby'?", answer: "F. Scott Fitzgerald" },
            { question: "What is the capital of Brazil?", answer: "Brasília" },
            { question: "Which element has the chemical symbol 'Au'?", answer: "Gold" },
            { question: "What is the longest mountain range in the world?", answer: "Andes" },
            { question: "Who discovered penicillin?", answer: "Alexander Fleming" },
            { question: "What is the capital of Egypt?", answer: "Cairo" },
            { question: "Which planet is closest to the Sun?", answer: "Mercury" },
            { question: "What is the largest type of whale?", answer: "Blue whale" },
            { question: "Who wrote '1984'?", answer: "George Orwell" },
            { question: "What is the capital of Russia?", answer: "Moscow" },
            { question: "Which gas do plants absorb from the atmosphere?", answer: "Carbon dioxide" },
            { question: "What is the largest island in the world?", answer: "Greenland" },
            { question: "Who painted 'The Scream'?", answer: "Edvard Munch" },
            { question: "What is the capital of South Africa?", answer: "Pretoria" },
            { question: "Which planet is known as the Earth's twin?", answer: "Venus" },
            { question: "What is the largest type of penguin?", answer: "Emperor penguin" },
            { question: "Who wrote 'To Kill a Mockingbird'?", answer: "Harper Lee" },
            { question: "What is the capital of Mexico?", answer: "Mexico City" },
            { question: "Which element has the chemical symbol 'Fe'?", answer: "Iron" },
            { question: "What is the largest ocean trench?", answer: "Mariana Trench" },
            { question: "Who invented the light bulb?", answer: "Thomas Edison" },
            { question: "What is the capital of Spain?", answer: "Madrid" },
            { question: "Which planet has the Great Red Spot?", answer: "Jupiter" },
            { question: "What is the largest type of shark?", answer: "Whale shark" },
            { question: "Who wrote 'The Catcher in the Rye'?", answer: "J.D. Salinger" },
            { question: "What is the capital of Italy?", answer: "Rome" },
            { question: "Which gas is used in balloons to make them float?", answer: "Helium" },
            { question: "What is the largest type of bear?", answer: "Polar bear" },
            { question: "Who painted 'Girl with a Pearl Earring'?", answer: "Johannes Vermeer" },
            { question: "What is the capital of Germany?", answer: "Berlin" },
            { question: "Which planet is known for its rings?", answer: "Saturn" },
            { question: "What is the largest type of big cat?", answer: "Siberian tiger" },
            { question: "Who wrote 'Brave New World'?", answer: "Aldous Huxley" },
            { question: "What is the capital of India?", answer: "New Delhi" },
            { question: "Which element has the chemical symbol 'H'?", answer: "Hydrogen" },
            { question: "What is the largest type of reptile?", answer: "Saltwater crocodile" },
            { question: "Who painted 'The Persistence of Memory'?", answer: "Salvador Dalí" },
            { question: "What is the capital of Argentina?", answer: "Buenos Aires" },
            { question: "Which planet rotates on its side?",
